######################################################################
# Automatically generated by qmake (2.01a) V márc. 15 16:16:34 2020
######################################################################

TEMPLATE = app
TARGET = myprog
DEPENDPATH += .
INCLUDEPATH += .

# Input
CONFIG += debug
HEADERS += firstmainwindow.h newcontactwindow.h searchdlg.h
SOURCES += firstmainwindow.cpp main.cpp newcontactwindow.cpp searchdlg.cpp
